name: Update Webpage Daily

on:
  schedule:
    - cron: '0 0 * * *'  # 每日00:00 UTC (台灣早上8:00)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - run: npm install
      - run: node index.js
      - name: Commit and push if changed
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@users.noreply.github.com'
          git add index.html
          git commit -m "每日自動更新資料" || echo "No changes"
          git push